services:
  ytdlp:
    build: .
    container_name: ytdlp
    ports:
      - "8080:80"
    networks:
      - main_network
    volumes:
      - ./.env:/code/.env

networks:
  main_network:
    external: true
